server:
  port: 9080
  servlet:
    contextPath: /vision
spring:
  aop:
    proxy-target-class: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  thymeleaf:
    cache: false

fixed:
  otp: 123456

es:
  esHost: localhost
  esPort: 9200

springdoc:
  swagger-ui:
    tagsSorter: alpha
    path: /swagger-ui
  api-docs:
    resolve-schema-properties: true
    path: /api-docs